name: scg-financial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.*
  - pandas=2.0.*
  - scipy=1.10.*
  - networkx=3.1.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - scikit-learn=1.2.*
  - statsmodels=0.14.*
  - pytorch=2.0.*
  - torchvision
  - torchaudio
  - jupyterlab=3.6.*
  - ipywidgets
  - tqdm
  - pytest=7.3.*
  - pylint=2.17.*
  - black=23.3.*
  - sphinx=6.2.*
  - sphinx_rtd_theme
  - nbsphinx
  - pandoc
  - pip
  - pip:
    - fredapi==0.5.*
    - yfinance==0.2.*
    - pyvis==0.3.*
    - networkx-metis==1.0.*
    - pmdarima==2.0.*
    - ta==0.10.*
    - plotly==5.14.*
    - dash==2.9.*
    - dash-bootstrap-components==1.4.*
    - pytest-cov==4.1.*
