from setuptools import setup, find_packages

setup(
    name="scr-financial-networks",
    version="0.1.0",
    description="Spectral Coarse-Graining for Financial Networks",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Francois Petizon",
    author_email="francois.petizon@kcl.ac.uk",
    url="https://github.com/username/scr-financial-networks",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Mathematics",
        "Topic :: Scientific/Engineering :: Information Analysis",
    ],
    python_requires=">=3.10",
    install_requires=[
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scipy>=1.10.0",
        "networkx>=3.1.0",
        "matplotlib>=3.7.0",
        "scikit-learn>=1.2.0",
        "torch>=2.0.0",
        "tqdm>=4.65.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.3.0",
            "black>=23.3.0",
            "flake8>=6.0.0",
            "isort>=5.12.0",
            "sphinx>=6.2.0",
            "sphinx_rtd_theme>=1.2.0",
            "nbsphinx>=0.9.0",
        ],
        "data": [
            "fredapi>=0.5.0",
            "yfinance>=0.2.0",
            "pyvis>=0.3.0",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
